CRITICAL - 2022-10-24 20:33:03 --> Object of class App\Entities\Usuario could not be converted to string
in APPPATH\Controllers\API\v1\Usuarios.php on line 50.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 20:36:02 --> Cannot use object of type App\Entities\Usuario as array
in APPPATH\Controllers\API\v1\Usuarios.php on line 50.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 20:36:26 --> Cannot use object of type App\Entities\Usuario as array
in APPPATH\Controllers\API\v1\Usuarios.php on line 50.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 20:36:43 --> Undefined constant "App\Controllers\API\v1\usu_correo"
in APPPATH\Controllers\API\v1\Usuarios.php on line 50.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 20:49:05 --> Unsupported operand types: string + string
in APPPATH\Controllers\API\v1\Usuarios.php on line 48.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 20:54:59 --> Unsupported operand types: string + string
in APPPATH\Controllers\API\v1\Usuarios.php on line 48.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-24 21:07:17 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:07:17 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:07:17 --> 
ERROR - 2022-10-24 21:07:47 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:07:47 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:07:47 --> 
ERROR - 2022-10-24 21:10:58 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:10:58 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:10:58 --> 
ERROR - 2022-10-24 21:11:38 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:11:38 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:11:38 --> 
ERROR - 2022-10-24 21:13:06 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:13:06 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:13:06 --> 
ERROR - 2022-10-24 21:13:17 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:13:17 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:13:17 --> 
ERROR - 2022-10-24 21:13:24 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:13:24 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:13:24 --> 
ERROR - 2022-10-24 21:13:41 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1730
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1730)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1730): mail('c.dzul@hotmail....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Mon, 24 O...', '-f antonio.dzul...')
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-10-24 21:13:41 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:13:41 --> 
ERROR - 2022-10-24 21:19:37 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for smtp.doinmobiliaria.com failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://smtp.doin...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:19:37 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:19:37 --> 
ERROR - 2022-10-24 21:20:17 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for smtp.doinmobiliaria.com failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://smtp.doin...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:20:17 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:20:17 --> 
ERROR - 2022-10-24 21:25:33 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for https failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://https://s...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:25:33 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:25:33 --> 
ERROR - 2022-10-24 21:29:35 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for smtp.doinmobiliaria.com failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://smtp.doin...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(67): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:29:35 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:29:35 --> 
ERROR - 2022-10-24 21:40:08 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(62): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:40:08 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:40:08 --> 
ERROR - 2022-10-24 21:40:08 --> Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Mon, 24 Oct 2022 21:40:08 -0600
From: &quot;TEST&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Email=20Test?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;63575a9802df12.40176040@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-24 21:45:08 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(62): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-24 21:45:08 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-24 21:45:08 --> 
ERROR - 2022-10-24 21:45:08 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Mon, 24 Oct 2022 21:45:08 -0600
From: &quot;TEST&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Email=20Test?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;63575bc42b3736.93424039@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
CRITICAL - 2022-10-24 21:50:24 --> Allowed fields must be specified for model: App\Models\UsuarioModel
in SYSTEMPATH\BaseModel.php on line 1159.
 1 SYSTEMPATH\BaseModel.php(1159): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\UsuarioModel')
 2 SYSTEMPATH\BaseModel.php(723): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 4 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 5 APPPATH\Controllers\API\v1\Usuarios.php(64): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 21:53:08 --> Call to undefined method App\Models\UsuarioModel::printDebugger
in SYSTEMPATH\Model.php on line 774.
 1 APPPATH\Controllers\API\v1\Usuarios.php(64): CodeIgniter\Model->__call('printDebugger', [...])
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:06:20 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1597.
 1 SYSTEMPATH\BaseModel.php(1597): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(708): CodeIgniter\BaseModel->transformDataToArray([], 'insert')
 3 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([], true)
 4 APPPATH\Controllers\API\v1\Usuarios.php(63): CodeIgniter\Model->insert([])
 5 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:26:17 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:26:40 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:27:11 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:27:36 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:27:51 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:28:31 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:28:51 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:29:22 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:29:38 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:31:25 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-24 22:33:18 --> Attempt to read property "usu_correo" on null
in APPPATH\Controllers\API\v1\Usuarios.php on line 52.
 1 APPPATH\Controllers\API\v1\Usuarios.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "usu_correo" on null', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-24 23:08:57 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\pulpox11\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pulpox11\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\pulpox11\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\pulpox11\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\pulpox11\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\pulpox11\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pulpox11\system\BaseModel.php(748): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pulpox11\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(68): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#9 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#10 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-10-24 23:08:57 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `usuarios_preregistro` (`usupr_correo`, `usupr_password`, `usupr_codigo_activacion`, `usupr_created_at`, `updated_at`) VALUES (\'c.dzul@hotmail.com\', \'123456789\', 123456, \'2022-10-24 23:08:57\', \'2022-10-24 23:08:57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios_preregistro` (`usupr_correo`, `usupr_password`, `usupr_codigo_activacion`, `usupr_created_at`, `updated_at`) VALUES (\'c.dzul@hotmail.com\', \'123456789\', 123456, \'2022-10-24 23:08:57\', \'2022-10-24 23:08:57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios_preregistro` (`usupr_correo`, `usupr_password`, `usupr_codigo_activacion`, `usupr_created_at`, `updated_at`) VALUES (\'c.dzul@hotmail.com\', \'123456789\', 123456, \'2022-10-24 23:08:57\', \'2022-10-24 23:08:57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_preregistro` (`usupr_correo`, `usupr_password`, `usupr_codigo_activacion`, `usupr_created_at`, `updated_at`) VALUES (:usupr_correo:, :usupr_password:, :usupr_codigo_activacion:, :usupr_created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\API\v1\Usuarios.php(68): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
